---
import:
  - project-zynqmp-default.yml
project:
  name: "test-project"
external_tools:
  xilinx:
    version: "2022.2"
blocks:
  atf:
    project:
      import_src: "https://serenity.web.cern.ch/sw/ci/os/branches/3-build-complete-serenity-s1-kria-k26-image-in-a-pipeline/0e10c5d1/pipeline7729069/serenity-s1-kria-atf.tar.gz"
  # rootfs:
  #   source: "build"
  #   builder: "ZynqMP_AMD_PetaLinux_RootFS_Builder"
  #   project:
  #     build_srcs:
  #       source: "https://github.com/Xilinx/yocto-manifests.git"
  #       branch: "rel-v{{external_tools/xilinx/version}}"
  #     add_build_info: true
  #     # If no 'import_src' property is specified, the block must be built locally
  #     dependencies:
  #       kernel: "temp/kernel/output/bp_kernel_*.tar.gz"
  #   container:
  #     image: "petalinux-rootfs-builder-alma8"
  #     tag: "socks"
  vivado:
    builder: "ZynqMP_AMD_Vivado_IPBB_Builder"
    project:
      build_srcs:
        - source: "https://github.com/ipbus/ipbus-firmware.git"
          branch: "-r 60d7efed3ddba10e551790de7505bfea5bfc738b"
        - source: "ssh://git@gitlab.cern.ch:7999/p2-xware/firmware/serenity-service.git"
          branch: "-b v0.4.4"
        - source: "ssh://git@gitlab.cern.ch:7999/p2-xware/zynq/serenity-s1-k26c-fw"
          branch: "-b main"
      name: "s1-kria"
    container:
      image: "ipbb-builder-alma8"
  # vivado:
  #   builder: "ZynqMP_AMD_Vivado_logicc_Builder"
  #   project:
  #     build_srcs:
  #       source: "ssh://git@gitlab.kit.edu/kit/ipe-sdr/ipe-sdr-dev/hardware/sdr_hardware.git"
  #       branch: "452-use-commit-id-of-sdr-hardware-instead-of-yocto-in-the-pimc"
  #     name: "cap_zcu216_echo"
  #   container:
  #     image: "logicc-builder-alma8"
  image:
    project:
      dependencies:
        ramfs: "temp/ramfs/output/bp_ramfs_*.tar.gz"
  rootfs:
    source: "build"
    builder: "ZynqMP_AlmaLinux_RootFS_Builder"
    project:
      release: "9"
      extra_rpms: ["gcc", "gcc-c++", "make", "dhclient", "python3-devel", "python3-click", "python3-numpy", "python3-pyserial", "glibc-headers", "glibc-devel", "zlib-devel", "libuuid ", "libuuid-devel", "pam-devel", "openldap-devel ", "pugixml-devel", "which", "gdb", "expect", "net-tools", "boost-chrono", "boost-regex", "boost-thread", "boost-filesystem", "boost-system", "boost-devel", "boost-program-options", "readline-devel", "emacs", "nano", "rsync", "git", "lighttpd", "strace", "minicom", "i2c-tools", "screen", "chrony", "rpm-build-libs", "rpm-build", "python3-pip", "nss", "nss-devel", "freeipmi", "cmake3", "log4cplus-devel", "yaml-cpp-devel", "msgpack-devel", "cppzmq-devel", "dosfstools", "libxml2-devel", "python3-libxml2", "python3-lxml", "libxml2 ", "libxslt ", "libxslt-devel", "python3-psutil", "python3-setuptools-wheel", "llvm-toolset", "dnf", "smash*"]
      # alma8 # extra_rpms: ["gcc", "gcc-c++", "make", "dhclient", "python3-devel", "python3-click", "python3-numpy", "python3-pyserial", "glibc-headers", "glibc-devel", "zlib-devel", "libuuid ", "libuuid-devel", "pam-devel", "openldap-devel ", "pugixml-devel", "gdb", "expect", "net-tools", "boost-chrono", "boost-regex", "boost-thread", "boost-filesystem", "boost-system", "boost-devel", "boost-program-options", "readline-devel", "emacs", "nano", "rsync", "git", "lighttpd", "strace", "minicom", "i2c-tools", "screen", "rpm-build-libs", "rpm-build", "python3-pip", "nss", "nss-devel", "freeipmi", "cmake3", "log4cplus-devel", "yaml-cpp-devel", "msgpack-devel", "cppzmq-devel", "dosfstools", "libxml2", "libxml2-devel", "python3-libxml2", "python3-lxml", "libxslt ", "libxslt-devel", "python3-psutil", "python3-setuptools-wheel", "llvm-toolset", "podman", "locmap-release", "locmap", "smash*"]
      build_time_fs_layer:
        - src_block: "vivado"
          src_name: "*.bit"
          dest_path: "/lib/firmware"
          dest_name: "serenity_s1_k26_pl.bit"
          dest_owner_group: "root:root"
          dest_permissions: "u=rw,go=r"
        - src_block: "devicetree"
          src_name: "*.dtbo"
          dest_path: "/etc/dt-overlays"
          dest_owner_group: "root:root"
          dest_permissions: "u=rwX,go=rX"
        - src_block: "vivado"
          src_name: "addrtab"
          dest_path: "/etc/serenity"
          dest_name: "zynq-addrtab"
      users:
        - name: "root"
          pw_hash: "$1$abFTnq2K$2Obyh.ZKwwExNujN/aCjQ." # alma
        - name: "kria"
          pw_hash: "$1$X6DWcY5/$GQ3ZFNgCGxOSgOZMT6Bkc1" # cms.higgs
          groups: ["wheel", "dialout"]
      add_build_info: false
      # If no 'import_src' property is specified, the block must be built locally
      dependencies:
        kernel: "temp/kernel/output/bp_kernel_*.tar.gz"
        devicetree: "temp/devicetree/output/bp_devicetree*.tar.gz"
        vivado: "temp/vivado/output/bp_vivado*.tar.gz"
    container:
      image: "alma9-rootfs-builder-alma9"
      tag: "socks"
  ramfs:
    source: "build"
    builder: "ZynqMP_BusyBox_RAMFS_Builder"
    project:
      build_srcs:
        source: "https://git.busybox.net/busybox/"
        branch: "1_36_1"
      add_build_info: false
      dependencies:
        kernel: "temp/kernel/output/bp_kernel_*.tar.gz"
    container:
      image: "busybox-ramfs-builder-alma9"
      tag: "socks"