#!/bin/sh

INTERFACE="eth0"
OFS_BASE="/mnt/overlayfs"
OFS_REMOTE="$OFS_BASE/ro"
OFS_LOWER="$OFS_REMOTE/lower"
OFS_LOCAL="$OFS_BASE/rw"
OFS_UPPER="$OFS_LOCAL/upper"
OFS_WORK="$OFS_LOCAL/work"
ROOT="/mnt/root"

fail(){
	printf "$1\n"
	sleep 0.1 # To ensure that the message is properly printed
  exit 1
}

echo "Executing init script of initramfs"
echo "This init script only supports mounting an overlayfs as rootfs"

# Mount temporary filesystems
mount -n -t devtmpfs devtmpfs /dev
mount -n -t proc     proc     /proc
mount -n -t sysfs    sysfs    /sys

# Create variables from Kernel command line parameters
for arg in "$@"; do
  # Split argument into key and value by the '=' sign
  IFS='=' read key value <<EOF
$arg
EOF
  # Declare the variable with its value
  eval "$key=$value"
done

# Check whether all required variables are available
if [ -z ${nfsshare+x} ]; then
  fail "Error: Unable to find parameter 'nfsshare' after '--' in the Kernel command line parameters"
fi
if [ -z ${localdev+x} ]; then
  fail "Error: Unable to find parameter 'localdev' after '--' in the Kernel command line parameters"
fi

while true; do
  # Bring up the network interface 
  ifup eth0

  # Wait until the interface has an IP address
  WAIT_INTERVAL=0.3  # Time to wait between checks
  TIMEOUT=10  # Timeout in wait intervals
  count=0
  while ! ip addr show "$INTERFACE" | grep -q "inet " && [ "$count" -lt "$TIMEOUT" ]; do
    echo "Waiting for IP address on $INTERFACE..."
    sleep $WAIT_INTERVAL
    count=`expr $count + 1`
  done
  
  # Check whether the timeout was reached 
  if [ "$count" -eq "$TIMEOUT" ]; then
    echo "Interface $INTERFACE did not come up. Try again..."
    # Bring down the network interface and try again 
    ifdown eth0
  else
    break
  fi
done

# Split variable for NFS mount
IFS=',' read nfs_location nfs_options <<EOF
$nfsshare
EOF

# Mount NFS share
mkdir -p $OFS_LOWER
eval "nfs_options=nolock,ro,$nfs_options"
printf "Mounting NFS share '$nfs_location' with options '$nfs_options'\n"
mount -t nfs -o $nfs_options $nfs_location $OFS_LOWER
if [ $? -ne 0 ]; then
    fail "Error: Could not mount nfs share"
fi

# Mount local device
mkdir -p $OFS_LOCAL
printf "Mounting local device '$localdev'\n"
mount $localdev $OFS_LOCAL
if [ $? -ne 0 ]; then
    fail "Error: Could not mount local device"
fi

# Create overlay file system
mkdir -p $OFS_UPPER
mkdir -p $OFS_WORK
mkdir -p $ROOT
printf "Mounting overlay file system\n"
mount -t overlay overlay -o lowerdir=$OFS_LOWER,upperdir=$OFS_UPPER,workdir=$OFS_WORK $ROOT
if [ $? -ne 0 ]; then
    fail "Error: could not mount overlay file system"
fi

# Move base mounts of the overlay file system to the new root directory
printf "Move base mounts to the overlay rootfs\n"
mkdir -p $ROOT/$OFS_LOWER
mount --move $OFS_LOWER $ROOT/$OFS_LOWER
if [ $? -ne 0 ]; then
    fail "Error: Could not move NFS mount into new root file system"
fi
mkdir -p $ROOT/$OFS_LOCAL
mount --move $OFS_LOCAL $ROOT/$OFS_LOCAL
if [ $? -ne 0 ]; then
    fail "Error: Could not move local mount into new root file system"
fi

# DEBUGGING
#exec /bin/sh

# Switch to new rootfs and exec init
printf "Switch to overlay rootfs\n"
cd $ROOT
exec switch_root . "/sbin/init" "$@"
