# project.yml
import:
  - project-raspberrypi-default.yml

project:
  name: "test-project"
  socks_version: "0.0.post1.dev276"
  rpi_model: "RPi_5"

external_tools:
  container_tool: "docker"

blocks:
  kernel:
    source: "build"
    builder: "RaspberryPi_Kernel_Builder"
    project:
      build_srcs:
        # Upstream RPi-Kernel-Branch (Beispiel)
        source: "https://github.com/raspberrypi/linux.git"
        branch: "rpi-6.12.y"
    container:
      image: "kernel-builder-alma9"
      tag: "socks"

  # U-Boot ist optional – nur aktivieren, wenn ihr es wirklich braucht:
  # ssbl:
  #   source: "build"
  #   builder: "RaspberryPi_UBoot_SSBL_Builder"
  #   project:
  #     build_srcs:
  #       source: "https://source.denx.de/u-boot/u-boot.git"
  #       branch: "v2025.07"
  #     add_build_info: false
  #     config_snippets:
  #       - Disable-efimkcapsule-command-to-circumvent-missing-dependencies.cfg
  #   container:
  #     image: "kernel-builder-alma9"
  #     tag: "socks"

  rootfs:
    source: "build"
    builder: "RaspberryPi_Debian_RootFS_Builder"
    project:
      release: "bookworm" 
      mirror: "http://ftp.de.debian.org/debian/"
      #release: "noble"
      #mirror: "https://ftp.uni-erlangen.de/ubuntu-ports/"
      addl_pkgs: ["sudo", "python3", "network-manager", "systemd-timesyncd", "openssh-server", "nano", "vim", "busybox", "device-tree-compiler"]
      # addl_pkgs:
      #   - sudo
      #   - python3
      #   - network-manager
      #   - systemd-timesyncd
      #   - openssh-server
      #   - nano
      #   - vim
      #   - device-tree-compiler
      #   - firmware-brcm80211 # WLAN/Bluetooth für RPi
      #   - linux-firmware
      users:
        - name: "root"
          pw_hash: "$6$socks$2J630pbW.yb.I2rf5KDImUoFLICgHjhb3Ugxpxgmahe68e2qkzZZ8veYQAwQRkjjwsuXqMEbO7oJ.vX6hIzbt1" # "computer"
        - name: "sdruser"
          pw_hash: "$6$socks$2J630pbW.yb.I2rf5KDImUoFLICgHjhb3Ugxpxgmahe68e2qkzZZ8veYQAwQRkjjwsuXqMEbO7oJ.vX6hIzbt1" # "computer"
          groups: ["sudo", "dialout"]
      add_build_info: true
      dependencies:
        kernel: "temp/kernel/output/bp_kernel_*.tar.gz"
    container:
      image: "debian-rootfs-builder-alma9"
      tag: "socks"

  image:
    source: "build"
    builder: "RaspberryPi_Image_Builder"
    project:
      size_boot_partition: 500
      size_rootfs_partition: 2000
      dependencies:
        kernel: "temp/kernel/output/bp_kernel_*.tar.gz"
        rootfs: "temp/rootfs/output/bp_rootfs_*.tar.gz"
        # ssbl: "temp/ssbl/output/bp_ssbl_*.tar.gz"   # nur falls U-Boot genutzt wird
