---
import:
  - project-raspberrypi-default.yml
project:
  name: "test-project"
  rpi_model: "RPi_5"
external_tools:
  container_tool: "docker"
blocks:
  kernel:
    project:
      build_srcs:
        branch: "rpi-6.12.y"
  ssbl:
    source: "build"
    builder: "RaspberryPi_UBoot_SSBL_Builder"
    project:
      build_srcs:
        source: "https://source.denx.de/u-boot/u-boot.git"
        branch: "v2025.07"
      # If no 'import_src' property is specified, the block must be built locally
      add_build_info: false
      config_snippets:
        - Disable-efimkcapsule-command-to-circumvent-missing-dependencies.cfg
    container:
      image: "kernel-builder-alma9"
      tag: "socks"
  # rootfs:
  #   source: "build"
  #   builder: "RaspberryPi_Debian_RootFS_Builder"
  #   project:
  #     release: "bookworm"
  #     mirror: "http://ftp.de.debian.org/debian/"
  #     addl_pkgs: ["sudo", "python3", "network-manager", "systemd-timesyncd", "openssh-server", "nano", "vim", "busybox", "device-tree-compiler"]
  #     users:
  #       - name: "root"
  #         pw_hash: "$6$YP9Y173jm8y4cD6R$b9b1duzuH0ryU8zFPl3TIGJ.yydRG3zW52dQjzIxoZVb4EVWiz.pyuwtCrS1dZ4TPr9faKftZ80jkzF75qk/a." # debian
  #       - name: "sdruser"
  #         pw_hash: "$6$yYrtPqck2CZ3HZwt$D6244woHxWVh6hvHBWXBs/KI5V44c4fYNs4wtfe1Kq15tulzpZOqlXl.Wvq8qgZc59h41wwCN1bjgeh2Y9yaM1" # cryo.daq
  #         groups: ["sudo", "dialout"]
  #     add_build_info: true
  #     dependencies:
  #       kernel: "temp/kernel/output/bp_kernel_*.tar.gz"
  #   container:
  #     image: "debian-rootfs-builder-debian12"
  #     tag: "socks"
  rootfs:
    source: "build"
    builder: "RaspberryPi_AlmaLinux_RootFS_Builder"
    project:
      release: "9"
      addl_pkgs: ["dnf"]
      # alma8 # addl_pkgs: ["gcc", "gcc-c++", "make", "dhclient", "python3-devel", "python3-click", "python3-numpy", "python3-pyserial", "glibc-headers", "glibc-devel", "zlib-devel", "libuuid ", "libuuid-devel", "pam-devel", "openldap-devel ", "pugixml-devel", "gdb", "expect", "net-tools", "boost-chrono", "boost-regex", "boost-thread", "boost-filesystem", "boost-system", "boost-devel", "boost-program-options", "readline-devel", "emacs", "nano", "rsync", "git", "lighttpd", "strace", "minicom", "i2c-tools", "screen", "rpm-build-libs", "rpm-build", "python3-pip", "nss", "nss-devel", "freeipmi", "cmake3", "log4cplus-devel", "yaml-cpp-devel", "msgpack-devel", "cppzmq-devel", "dosfstools", "libxml2", "libxml2-devel", "python3-libxml2", "python3-lxml", "libxslt ", "libxslt-devel", "python3-psutil", "python3-setuptools-wheel", "llvm-toolset", "podman", "locmap-release", "locmap"]
      users:
        - name: "root"
          pw_hash: "$1$abFTnq2K$2Obyh.ZKwwExNujN/aCjQ." # alma
        - name: "kria"
          pw_hash: "$1$X6DWcY5/$GQ3ZFNgCGxOSgOZMT6Bkc1" # cms.higgs
          groups: ["wheel", "dialout"]
      add_build_info: true
      # If no 'import_src' property is specified, the block must be built locally
      dependencies:
        kernel: "temp/kernel/output/bp_kernel_*.tar.gz"
    container:
      image: "alma9-rootfs-builder-alma9"
      tag: "socks"
  image:
    project:
      size_boot_partition: 500
      size_rootfs_partition: 2000
      dependencies:
        # ssbl: "temp/ssbl/output/bp_ssbl_*.tar.gz"
        rootfs: "temp/rootfs/output/bp_rootfs_*.tar.gz"
