import sys
import pathlib
import inspect

import socks.pretty_print as pretty_print
from socks.build_validator import Build_Validator
from amd_zynqmp_support.zynqmp_amd_kernel_builder import ZynqMP_AMD_Kernel_Builder
from raspberrypi_support.raspberrypi_kernel_model import RaspberryPi_Kernel_Model


class RaspberryPi_Kernel_Builder(ZynqMP_AMD_Kernel_Builder):
    """
    Raspberry Pi Kernel builder class
    """

    def __init__(
        self,
        project_cfg: dict,
        socks_dir: pathlib.Path,
        project_dir: pathlib.Path,
        block_id: str = "kernel",
        block_description: str = "Build the official Raspberry Pi version of the Linux Kernel",
        model_class: type[object] = RaspberryPi_Kernel_Model,
    ):

        super().__init__(
            project_cfg=project_cfg,
            socks_dir=socks_dir,
            project_dir=project_dir,
            block_id=block_id,
            block_description=block_description,
            model_class=model_class,
        )

        self.pre_action_warnings.append("This block is experimental, it should not be used for production.")

        # Project files
        # File for version & build info tracking
        self._rpi_model_file = self._block_src_dir / "rpi_model.txt"

    def validate_srcs(self):
        """
        Check whether all sources required to build this block are present.

        Args:
            None

        Returns:
            None

        Raises:
            None
        """

        super().validate_srcs()

        # Check whether this block is configured for the Raspberry Pi model specified in the project configuration
        try:
            with open(self._rpi_model_file, mode="r", newline="") as file:
                config_rpi_mode = file.readlines()[1].strip()

            if config_rpi_mode != self.project_cfg.project.rpi_model:
                pretty_print.print_error(
                    f"Configuration missmatch. Block '{self.block_id}' is configured for '{config_rpi_mode}', "
                    f"but the project cofiguration is for '{self.project_cfg.project.rpi_model}'.\n"
                    f"Please clean this block and delete the following directory manually: '{self._block_src_dir}'"
                )
                sys.exit(1)
        except FileNotFoundError:
            pass  # It is okay if the file does not exist

    def prep_clean_srcs(self):
        """
        This function is intended to create a new, clean Linux kernel or U-Boot project. After the creation
        of the project you should create a patch that includes .gitignore and .config.

        Args:
            None

        Returns:
            None

        Raises:
            None
        """

        prep_srcs_commands = [
            f"cd {self._source_repo_dir}",
            "export CROSS_COMPILE=aarch64-linux-gnu-",
        ]

        if self.project_cfg.project.rpi_model == "RPi_4B":
            prep_srcs_commands.append("make ARCH=arm64 bcm2711_defconfig")
        elif self.project_cfg.project.rpi_model == "RPi_5":
            prep_srcs_commands.append("make ARCH=arm64 bcm2712_defconfig")
        else:
            raise ValueError(
                f"The following Raspberry Pi Model is not supported: '{self.project_cfg.project.rpi_model}'"
            )

        prep_srcs_commands.append('printf "\n# Do not ignore the config file\n!.config\n" >> .gitignore')

        super()._prep_clean_srcs(prep_srcs_commands=prep_srcs_commands)

        # Save the Raspberry Pi model for which the block is now configured to a file
        self._rpi_model_file.parent.mkdir(parents=True, exist_ok=True)
        with open(self._rpi_model_file, mode="w", newline="") as file:
            file.write(
                "# This file is autogenerated to validate the block configuration, "
                f"do not edit!\n{self.project_cfg.project.rpi_model}"
            )

    def build_kernel(self):
        """
        Builds the Linux Kernel.

        Args:
            None

        Returns:
            None

        Raises:
            None
        """

        # Check whether the Kernel needs to be built
        if not Build_Validator.check_rebuild_bc_timestamp(
            src_search_list=[self._source_repo_dir],
            src_ignore_list=[self._source_repo_dir / "arch/arm64/boot"],
            out_timestamp=self._build_log.get_logged_timestamp(
                identifier=f"function-{inspect.currentframe().f_code.co_name}-success"
            ),
        ) and not self._build_validator.check_rebuild_bc_config(
            keys=[["blocks", self.block_id, "project", "add_build_info"]]
        ):
            pretty_print.print_build("No need to rebuild the Linux Kernel. No altered source files detected...")
            return

        with self._build_log.timestamp(identifier=f"function-{inspect.currentframe().f_code.co_name}-success"):
            # Remove old build artifacts
            (self._output_dir / "Image").unlink(missing_ok=True)
            (self._output_dir / "Image.gz").unlink(missing_ok=True)
            if self.project_cfg.project.rpi_model == "RPi_4B":
                (self._output_dir / "bcm2711-rpi-4-b.dtb").unlink(missing_ok=True)
            elif self.project_cfg.project.rpi_model == "RPi_5":
                (self._output_dir / "bcm2712d0-rpi-5-b.dtb").unlink(missing_ok=True)
                (self._output_dir / "bcm2712-d-rpi-5-b.dtb").unlink(missing_ok=True)
                (self._output_dir / "bcm2712-rpi-5-b.dtb").unlink(missing_ok=True)
            else:
                raise ValueError(
                    f"The following Raspberry Pi Model is not supported: '{self.project_cfg.project.rpi_model}'"
                )

            pretty_print.print_build("Building Linux Kernel...")

            if self.block_cfg.project.add_build_info == True:
                # Add build information file
                with self._build_info_file.open("w") as f:
                    print('const char *build_info = "', file=f, end="")
                    print(self._compose_build_info().replace("\n", "\\n"), file=f, end="")
                    print('";', file=f, end="")
            else:
                # Remove existing build information file
                self._build_info_file.unlink(missing_ok=True)

            kernel_build_commands = [
                f"cd {self._source_repo_dir}",
                "export CROSS_COMPILE=aarch64-linux-gnu-",
                "make ARCH=arm64 olddefconfig",
                "git update-index --assume-unchanged .config",  # Normally .config is in the gitignore file, so the kernel should not be dirty because of this. .config is sometimes changed automatically due to the container used.
                f"make ARCH=arm64 -j{self.project_cfg.external_tools.make.max_build_threads}",
                "git update-index --no-assume-unchanged .config",  # Stop hiding .config
            ]

            self.container_executor.exec_sh_commands(
                commands=kernel_build_commands,
                dirs_to_mount=[(self._repo_dir, "Z")],
                print_commands=True,
                logfile=self._block_temp_dir / "build.log",
                output_scrolling=True,
            )

            # Create symlink to the output files
            (self._output_dir / "Image").symlink_to(self._source_repo_dir / "arch/arm64/boot/Image")
            (self._output_dir / "Image.gz").symlink_to(self._source_repo_dir / "arch/arm64/boot/Image.gz")
            if self.project_cfg.project.rpi_model == "RPi_4B":
                (self._output_dir / "bcm2711-rpi-4-b.dtb").symlink_to(
                    self._source_repo_dir / "arch/arm64/boot/dts/broadcom/bcm2711-rpi-4-b.dtb"
                )
            elif self.project_cfg.project.rpi_model == "RPi_5":
                (self._output_dir / "bcm2712d0-rpi-5-b.dtb").symlink_to(
                    self._source_repo_dir / "arch/arm64/boot/dts/broadcom/bcm2712d0-rpi-5-b.dtb"
                )
                (self._output_dir / "bcm2712-d-rpi-5-b.dtb").symlink_to(
                    self._source_repo_dir / "arch/arm64/boot/dts/broadcom/bcm2712-d-rpi-5-b.dtb"
                )
                (self._output_dir / "bcm2712-rpi-5-b.dtb").symlink_to(
                    self._source_repo_dir / "arch/arm64/boot/dts/broadcom/bcm2712-rpi-5-b.dtb"
                )
            else:
                raise ValueError(
                    f"The following Raspberry Pi Model is not supported: '{self.project_cfg.project.rpi_model}'"
                )
