from pydantic import BaseModel, Field, ConfigDict, StringConstraints
from typing_extensions import Annotated
from typing import Optional

from abstract_builders.block_model import Block_Model, Block_Project_Model, Block_Project_Model_Default_Fields
from abstract_builders.file_system_model import (
    File_System_Installable_Build_Time_Item_Model,
    File_System_Custom_Package_Model,
    File_System_User_Model,
)


class Debian_RootFS_Dependencies_Model(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)

    kernel: str
    devicetree: Optional[str] = None
    vivado: Optional[str] = None


class Debian_RootFS_Block_Project_Model(Block_Project_Model):
    model_config = ConfigDict(extra="forbid", strict=True)

    release: Annotated[str, StringConstraints(pattern=r"^[a-z]+$")] = Field(
        default=..., description="Release version of the OS to be built"
    )
    mirror: Annotated[str, StringConstraints(pattern=r"^http:\/\/.*debian.*")] = Field(
        default="http://ftp.de.debian.org/debian/", description="Debian mirror to be used"
    )
    addl_pkgs: Optional[list[str]] = Field(default=None, description="List of additional deb packages to be installed")
    addl_ext_pkgs: Optional[list[str]] = Field(
        default=None, description="List of additional packages to be installed from external *.deb files"
    )
    build_time_fs_layer: Optional[list[File_System_Installable_Build_Time_Item_Model]] = Field(
        default=None,
        description="List of files and directories to be installed that were generated by other blocks at build time",
    )
    custom_pkgs: Optional[list[File_System_Custom_Package_Model]] = Field(
        default=None,
        description="List of custom packages to be built. These packages typically use files generated by other blocks.",
    )
    users: list[File_System_User_Model] = Field(default=None, description="List of users to be added")
    add_build_info: bool = Block_Project_Model_Default_Fields.add_build_info
    dependencies: Debian_RootFS_Dependencies_Model = Block_Project_Model_Default_Fields.dependencies


class Debian_RootFS_Block_Model(Block_Model):
    model_config = ConfigDict(extra="forbid", strict=True)

    project: Debian_RootFS_Block_Project_Model


class Debian_RootFS_Blocks_Model(BaseModel):
    model_config = ConfigDict(extra="ignore")

    rootfs: Debian_RootFS_Block_Model = Field(
        default=..., description="Configuration of the Debian root file system block"
    )
