---
import:
  - project-zynqmp-default.yml
project:
  name: "test-project"
externalTools:
  xilinx:
    path: "/media/marvin/T9MF/Tools/Xilinx"
    version: 2022.2
    license: "50000@ipeflex1.ipe.kit.edu"
blocks:
  atf:
    project:
      pre-built: "https://serenity.web.cern.ch/sw/ci/os/branches/3-build-complete-serenity-s1-kria-k26-image-in-a-pipeline/0e10c5d1/pipeline7729069/serenity-s1-kria-atf.tar.gz"
  vivado:
    builder: "ZynqMP_AMD_Vivado_Hog_Builder_Alma9"
    project:
      sources: "ssh://git@gitlab.cern.ch:7999/p2-xware/zynq/serenity-s1-k26c-fw.git"
      branch: "test"
      name: "serenity-s1-kria"
  rootfs:
    project:
      add-build-info: True
#  rootfs:
#    source: "build"
#    builder: "ZynqMP_Alma_RootFS_Builder_Alma8"
#    release: "8"
#    project:
#      add-build-info: false
#      # If no 'pre-built' property is specified, the block must be built locally
#      dependencies:
#        kernel: "temp/kernel/output/kernel.tar.gz"
#        devicetree: "temp/devicetree/output/devicetree.tar.gz"
#        vivado: "temp/vivado/output/vivado.tar.gz"
#    container:
#      image: "alma8-rootfs-builder-alma8"
#      tag: "xilinx-v{{externalTools/xilinx/version}}"
